### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Marwan2001** [Marwan2001/Python_Projects#1]
Add anything

**Comment by pranavgoel25** [comment]
Please see pull request #12

**Comment by pranavgoel25** [comment]
Please see #14 . Added a new project

**Comment by CrazyLlama** [comment]
#17  😄 @Marwan2001

**Comment by jalbertsr** [comment]
please take a look at #19 added new sorting algorithms project.

**Comment by pranavgoel25** [comment]
Please look at #23 . Added new project

**Comment by Jerry2001** [comment]
Sorry, I want to push a python file which is a bot for Facebook messenger but I got denied in master branch....

**Comment by jarvmiller** [comment]
See #33. A nice program to dissect and use for your own purposes

**Comment by Busterz** [comment]
please see #42 😄 @Marwan2001

**Comment by KristofArron** [comment]
Have a look at [#43](https://github.com/Marwan2001/Python_Projects-/pull/43). I've added something that I think will fit nicely in this repo.

**Comment by jalbertsr** [comment]
please @Marwan2001 take a look at  #48 is a solution for the knapsack problem

**Comment by fercreek** [comment]
My PR #11 is to add virtualenv. @Marwan2001

**Comment by Noxime** [comment]
Add FizzBuzz algorithm: #22

**Comment by harryjas** [comment]
Added a python3 script geolocator.py that gives location(State, Country, Latitude and Longitude) of the entered city.
Check it out https://github.com/Marwan2001/Python_Projects-/pull/66

**Comment by pBouillon** [comment]
Check #67 I corrected a huge parts of your code !

**Comment by pranavgoel25** [comment]
Please see #71

**Comment by pBouillon** [comment]
#72 submitted

**Comment by namish800** [comment]
@Marwan2001  Review my PR https://github.com/Marwan2001/Python_Projects-/pull/73

**Comment by RodolfoFerro** [comment]
Hey @Marwan2001 , awesome project !

I've added some scripts, as you can see in https://github.com/Marwan2001/Python_Projects/pull/76:

* circle_detection.py - Detects circles on video camera using OpenCV.
* epotential.py - Computes electric potential.
* nelder_mead.py - Nelder-Mead minimization algorithm.
* pi.py - Approximation of π using Monte Carlo.
* plot_example.py - An example of plotting a simple function using matplotlib.
* quiver.py - An example of using matplotlib's quiver.

Hope you aprove this PR. :octocat: 👍

**Comment by Mask123pru** [comment]
https://github.com/Marwan2001/Python_Projects/pull/82 Review this PR implemented a website blocker

**Comment by pranavgoel25** [comment]
Please see #86

**Comment by ChrisHersh** [comment]
Added #101
